### ISSUE TITLE
`import NutMEG` fails with `reaktoro` error

### ISSUE THREAD

**Issue by colemathis** [pmhiggins/NutMEG#16]
Unable to import NutMEG with fresh clone. 

Used Conda to install `reaktoro` but I think the `reaktoro` has been updated and the naming conventions have changed. 

Python is unable to import `Thermo` 

```
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import NutMEG
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\cmathis6\Desktop\Scratch\NutMEG_tests\NutMEG\NutMEG\__init__.py", line 13, in <module>
    from .culture.base_organism.base_organism import base_organism
  File "C:\Users\cmathis6\Desktop\Scratch\NutMEG_tests\NutMEG\NutMEG\culture\__init__.py", line 2, in <module>
    from .base_organism.respirator import respirator
  File "C:\Users\cmathis6\Desktop\Scratch\NutMEG_tests\NutMEG\NutMEG\culture\base_organism\respirator.py", line 5, in <module>
    from NutMEG import reaction as rxn
  File "C:\Users\cmathis6\Desktop\Scratch\NutMEG_tests\NutMEG\NutMEG\reaction\__init__.py", line 16, in <module>
    from .reaction import reaction
  File "C:\Users\cmathis6\Desktop\Scratch\NutMEG_tests\NutMEG\NutMEG\reaction\reaction.py", line 15, in <module>
    from NutMEG.reaction.thermo.reaction_thermo import reaction_thermo
  File "C:\Users\cmathis6\Desktop\Scratch\NutMEG_tests\NutMEG\NutMEG\reaction\thermo\reaction_thermo.py", line 11, in <module>
    from reaktoro import Database, Thermo
ImportError: cannot import name 'Thermo' from 'reaktoro' (C:\Miniconda3\lib\site-packages\reaktoro\__init__.py)

```

**Comment by pmhiggins** [comment]
Hi @colemathis 

Thanks for raising this. You are correct, `reaktoro` has recently released v2 and as far as I know the `Thermo` class is yet to be implemented. See [this issue](https://github.com/reaktoro/reaktoro/issues/222) raised when a colleague of mine had a similar problem.

Try specifying `reaktoro` version 1 when installing it e.g. `conda install reaktoro=1` or similar. There is more information available in the [reaktoro v1 docs](https://reaktoro.org/v1/installation.html).

~ Pete

**Comment by allanleal** [comment]
Hi guys, I just found this issue (which got listed in this Reaktoro issue https://github.com/reaktoro/reaktoro/issues/222).

In Reaktoro v2, the `Thermo` class is not needed anymore. Please check the following tutorials to learn the new way of computing standard thermodynamic properties of species and reactions:

* [Computing standard thermodynamic properties of species](https://reaktoro.org/tutorials/basics/computing-thermo-props-of-species.html)
* [Computing standard thermodynamic properties of reactions](https://reaktoro.org/tutorials/basics/computing-thermo-props-of-reactions.html)

Feedback is appreciated! ;)

These tutorials are a work in progress. Let me know if they suffice to what you need.
